### PR TITLE
Update installation and CI status url to match repo url

### PR DESCRIPTION
**Pull request by russellsanborn**
I also updated the command from `asdf plugin-add` to `asdf plugin add` to match the official documentation.

Reference:
https://asdf-vm.com/manage/plugins.html

### CODE REVIEW

**Comment by kennyp** [comment]
Thanks for the PR @russellsanborn. We should probably update the CI badge as well.

**Comment by kennyp** [comment]
If you're game to do it real quick that would be great! Thanks!

**Review by kennyp — APPROVED** [review]
LGTM

**Comment by russellsanborn** [comment]
As a reference, i submitted a PR to update the links in asdf-plugins.

https://github.com/asdf-vm/asdf-plugins/pull/860

**Pull request merged**
